### ISSUE TITLE
Add youtube link to videos

### ISSUE THREAD

**Issue by simonegiacomelli** [CuriousDrive/BlazingChat#2]
Hi! Thanks for your very helpful youtube channel and related github repo 👍 

I created a pull request to link the youtube videos but I realized that it was the wrong link!

Could you add the link in the README?

**Comment by CuriousDrive** [comment]
Thanks for raising this issue. I have updated the README file explaining how to run this app and from where you can watch the tutorials.

**Comment by CuriousDrive** [comment]
Thanks for raising this issue. I have updated the README file explaining how to run this app and from where you can watch the tutorials.
