### ISSUE TITLE
JWT Authorization for Google & Twitter Login

### ISSUE THREAD

**Issue by CuriousDrive** [CuriousDrive/BlazingChat#21]
Just like how we added JWT authorization for Facebook. We need to add same for Google & Twitter login

**Comment by CuriousDrive** [comment]
This has been fixed. I had to remove Google auth. Google is being difficult :(

**Comment by eddedre** [comment]
@CuriousDrive Are there any plans to revisit Google Auth?

**Comment by valentasm1** [comment]
@CuriousDrive Are there any plans to revisit Google Auth?
