### ISSUE TITLE
"Sorry, there's nothing at this address." when clicking on the Sign in with Twitter, Facebook or Google buttons

### ISSUE THREAD

**Issue by In2Creation** [CuriousDrive/BlazingChat#4]
Hi,

Ik just downloaded and tried to run the BlazingChat solution "Episode_15".
When running the website I navigate to "Profile" and click the Sign in with "Twitter", "Google" or "Facebook" button.
This always redirects me to the page not found page.

Is there some routing missing for the server controllers?

Kind regards,

Jan

**Comment by CuriousDrive** [comment]
Hello In2Creation,

Thanks for trying out BlazingChat. Sometimes blazor assemblies stay in the browser cache. If you were working on authorization for your project and then loaded my project sometimes it does not work.

Please clear your cache and hard refresh the browser to see it is working for you or not. I tried this at my end this morning and it is working for me. Let me know, 

Thanks
Fahad Mullaji

**Comment by In2Creation** [comment]
Hi Fahad,

Thanks for your quick response!

I already tried clearing the cache in Google Chrome without any changes. I tested your solution in Google Chrome, Edge and FireFox. All with the same result.
![image](https://user-images.githubusercontent.com/12663769/105754044-deca8e00-5f49-11eb-87b8-133e37e7f07f.png)

If I then click on Sign in with Google
![image](https://user-images.githubusercontent.com/12663769/105754119-f7d33f00-5f49-11eb-938d-253151bf540c.png)

I am running your solution with the latest Visual Studio 2019 Community (16.8.4)

Kind Regard,

Jan

**Comment by djordjedjukic** [comment]
I gave the same problem.

Any ideas what can be the problem?

**edit1:**
It doesn't work in browser window which is launched on application startup. But if I copy link in regular chrome window, it works.
Also it doesn't work in firefox or edge. Really strange

**edit2:**
Now it doesn't work anywhere.

**Comment by CuriousDrive** [comment]
Hello, 

Some other viewers are also facing the same issue. I'd say debug and see if you are facing any exceptions while authenticating. It might be because of how your Facebook/Google/Twitter account info is setup and my program is not able to handle that info. 
I am gonna need more log info to figure out why this is not working for. Because as you can see in the video it is working for me

Thanks
Fahad Mullaji

**Comment by CuriousDrive** [comment]
This issue has been fixed with JWT authentication. I had to remove Google authentication from the app. Google is being pain in the neck. But other auth types are working fine. 
I am closing this issue. Let me know if you are still facing this issue.
