### ISSUE TITLE
Not found: https://localhost:5001/signin-google?state=Cf 

### ISSUE THREAD

**Issue by martinmichaelsen** [CuriousDrive/BlazingChat#5]
Hello all.

Thanks for these awesome samples:-) I am trying to get Google auth going and I've replicated the steps in Episode15. I am getting some of the way (my Controller was hit, I select my Google user) but I end up with https://localhost:5001/signin-google?state=Cf.......... not found.
I seems that I am missing something somewhere?
Kind regards
Martin

**Comment by CuriousDrive** [comment]
There's already an issue #4 logged for this. Let's continue discussion there :)
