### ISSUE TITLE
Run BlazingChat as a Blazor Server.

### ISSUE THREAD

**Issue by CuriousDrive** [CuriousDrive/BlazingChat#66]
It's time to switch between Blazor Server and WebAssembly

**Comment by tesar-tech** [comment]
Another step to making BlazinChat more user friendly: Hybrid solution. https://itnext.io/blazor-switching-server-and-webassembly-at-runtime-d65c25fd4d8

**Comment by CuriousDrive** [comment]
> Another step to making BlazinChat more user friendly: Hybrid solution. https://itnext.io/blazor-switching-server-and-webassembly-at-runtime-d65c25fd4d8

**Comment by CuriousDrive** [comment]
> Another step to making BlazinChat more user friendly: Hybrid solution. https://itnext.io/blazor-switching-server-and-webassembly-at-runtime-d65c25fd4d8

Interesting. I will keep it in mind. The implementation should make sense for BlazingChat and need to be easier to explain in a video
